'use client';
import { useEffect } from 'react';
import Head from 'next/head';
import Image from "next/image";
import localFont from "next/font/local";
import Curve from '../components/Layout/Curve';
import Intro from '../components/Intro';
import Description from '../components/Description';
import Header from '../components/Header';
import Gallery from '../components/Gallery';
import Contact from '../components/Contact';


import { projects } from '../components/Gallery';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export default function Home() {
  useEffect(() => {
    (
      async () => {
      const LocomotiveScroll = (await import("locomotive-scroll")).default;
      const locomotiveScroll = new LocomotiveScroll();
    }
    )()
  }, [])

  return (
    <>
      <Head>
        <title>Looplight Art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <div className='main'>
          <Header />
          <Intro />
          <Description/>
          <div className='gap'></div>
          {
            projects.map( ({handle, title, description}, index) => {
              return <Gallery handle={handle} title={title} description={description} key={index}></Gallery>
            })
          }
          <div className='para'></div>
          <Contact />
        </div>
      </Curve>
    </>
  );
}
